import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind CSS Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-slate-100 min-h-screen">
        <nav className="flex justify-between items-center bg-teal-500 py-3 px-8">
          <div className="font-bold text-2xl">VK</div>
        </nav>
      </div>
    </div>
  );
}
